-- Databricks notebook source
-- =============================================================================
-- field_service — vibe MODEL setup (READ-ONLY, NORMALIZED 3NF spec)
-- =============================================================================
-- Stands up the FAST-LOOP test domain's vibe model: the vibe_metamodel_* tables
-- the domain-model-assessment skill reads in Phase 1, plus the EMPTY target shells
-- with PKs / FK constraints / comments / glossary tags so information_schema reads
-- return real structure.
--
-- SHAPE: the vibe model is a NORMALIZED, 3NF, single-source-of-truth SPEC — one
-- table per business entity, natural business keys as PKs (customer_id,
-- service_order_id, asset_id), snake_case product names, NO dim_/fact_ prefixes,
-- NO SHA2 surrogate keys. Both output_model flows build FROM this seed:
--   - dimensional flow  -> derives dim_/fact_ star + SHA2 surrogates (field_service_silver_dim)
--   - normalized flow   -> ports these tables 1:1 (field_service_silver_norm)
--
-- This is the READ-ONLY model location (conventions -> vibe_model.*). The ETL build
-- LANDS output into a SEPARATE catalog (catalogs.silver). Never point a build here.
--
-- Source bronze already exists: meridian_bronze.fieldlink + .sap_sd
-- (generated by examples/setup/data_generator). This script does NOT touch bronze.
--
-- Run once. Idempotent: CREATE OR REPLACE on metamodel tables; shells dropped +
-- recreated. Catalog/schema are runtime params (widgets), never hard-coded.
-- =============================================================================

-- COMMAND ----------
-- Runtime params — the deployed READ location.
CREATE WIDGET TEXT vibe_model_catalog DEFAULT 'meridian_model';
CREATE WIDGET TEXT vibe_model_schema  DEFAULT 'field_service_model';

-- COMMAND ----------
-- Set session context so all UNQUALIFIED refs below resolve to the model location.
CREATE SCHEMA IF NOT EXISTS IDENTIFIER(:vibe_model_catalog || '.' || :vibe_model_schema);
USE CATALOG IDENTIFIER(:vibe_model_catalog);
USE SCHEMA  IDENTIFIER(:vibe_model_schema);

-- COMMAND ----------
-- Drop any prior (e.g. dimensional) shells so a re-run lands a clean normalized model.
DROP TABLE IF EXISTS fact_service_order;
DROP TABLE IF EXISTS dim_installed_asset;
DROP TABLE IF EXISTS dim_technician;
DROP TABLE IF EXISTS dim_product;
DROP TABLE IF EXISTS dim_customer;
DROP TABLE IF EXISTS service_order;
DROP TABLE IF EXISTS installed_asset;
DROP TABLE IF EXISTS technician;
DROP TABLE IF EXISTS product;
DROP TABLE IF EXISTS customer;

-- COMMAND ----------
-- =============================================================================
-- METAMODEL TABLE 1: vibe_metamodel_business  (assessment Phase 1.1)
-- =============================================================================
CREATE OR REPLACE TABLE vibe_metamodel_business (
  business_name                 STRING,
  industry                      STRING,
  operational_systems_of_records STRING,   -- comma list — scopes the bronze search
  common_jargon                 STRING,
  modelling_conventions         STRING,
  data_asset_naming_convention  STRING,
  primary_key_suffix            STRING,
  boolean_format                STRING,
  date_format                   STRING,
  timestamp_format              STRING
);

INSERT INTO vibe_metamodel_business VALUES (
  'Meridian Fluid Controls',
  'Industrial manufacturing — field service & installed base',
  'FieldLink (field-service app), SAP S/4HANA SD (customer master)',
  'asset is an installed valve/actuator unit at a customer site; service order is a dispatched field job on an asset; technician is the field engineer who performs the work; commissioning is first successful install.',
  '3NF normalized; one table per business entity; natural business keys; no surrogate keys; snake_case singular tables and columns.',
  'snake_case singular entity names; no dim_/fact_ prefix (normalized SSOT model)',
  '_id',
  'true/false',
  'yyyy-MM-dd',
  'yyyy-MM-dd HH:mm:ss'
);

-- COMMAND ----------
-- =============================================================================
-- METAMODEL TABLE 2: vibe_metamodel_product  (assessment Phase 1.2)
--   type: Master / Transactional — intent the DIMENSIONAL flow uses to pick dim vs fact.
--   table_name: the model's normalized product table name (used verbatim by the
--   normalized flow; the dimensional flow adds dim_/fact_ prefixes).
-- =============================================================================
CREATE OR REPLACE TABLE vibe_metamodel_product (
  product      STRING,
  table_name   STRING,
  type         STRING,
  subdomain    STRING,
  primary_key  STRING,
  description  STRING
);

INSERT INTO vibe_metamodel_product VALUES
  ('service_order',   'service_order',   'Transactional', 'service', 'service_order_id',
   'One row per dispatched field-service job on an installed asset. Grain: service_order_id. FKs to installed_asset and technician; customer and product are reached transitively through the asset.'),
  ('installed_asset', 'installed_asset', 'Master', 'asset', 'asset_id',
   'One row per serialized installed unit at a customer site. Sourced from FieldLink installed_asset; FKs to customer (via kunnr) and product (via sku_code).'),
  ('customer',        'customer',        'Master', 'party', 'customer_id',
   'One row per customer account. Sourced from SAP kna1 — natural key kunnr. Cross-source: reached from FieldLink assets via installed_asset.customer_kunnr.'),
  ('product',         'product',         'Master', 'material', 'product_id',
   'One row per SKU installed in the field. Sourced from the distinct SKU attributes carried on FieldLink installed_asset (sku_code, product_group).'),
  ('technician',      'technician',      'Master', 'party', 'technician_id',
   'One row per field-service technician. Intended master for the technician who performs a service order. (No clean bronze source — see gap.)');

-- COMMAND ----------
-- =============================================================================
-- METAMODEL TABLE 3: vibe_metamodel_attribute  (assessment Phase 1.3)
--   foreign_key_to: {product}.{pk} — includes cross-domain refs w/ no physical FK
--   value_regex: allowed value patterns / enum sets
-- =============================================================================
CREATE OR REPLACE TABLE vibe_metamodel_attribute (
  product               STRING,
  attribute             STRING,
  type                  STRING,
  business_glossary_term STRING,
  value_regex           STRING,
  foreign_key_to        STRING,
  description           STRING
);

INSERT INTO vibe_metamodel_attribute VALUES
  -- service_order (Transactional)
  ('service_order','service_order_id','STRING','Service Order Number','^SO[0-9]{8}$',NULL,'PK — natural key, FieldLink service_order_id'),
  ('service_order','asset_id','STRING','Asset Number','^AST[0-9]{8}$','installed_asset.asset_id','FK to installed_asset'),
  ('service_order','technician_id','STRING','Technician Id',NULL,'technician.technician_id','FK to technician — NO clean bronze source (only a free-text name on service_order.technician). Gap.'),
  ('service_order','order_type','STRING','Service Order Type','^(preventive|corrective|inspection|calibration)$',NULL,'Type of field job'),
  ('service_order','opened_date','DATE','Service Order Opened Date',NULL,NULL,'Date the job was opened'),
  ('service_order','status','STRING','Service Order Status','^(open|dispatched|completed|closed)$',NULL,'Lifecycle status'),
  ('service_order','priority','STRING','Service Order Priority','^(low|medium|high|critical)$',NULL,'Dispatch priority'),
  -- installed_asset (Master)
  ('installed_asset','asset_id','STRING','Asset Number','^AST[0-9]{8}$',NULL,'PK — natural key, FieldLink asset_id'),
  ('installed_asset','serial_number','STRING','Serial Number','^SN[0-9]{8}$',NULL,'Unit serial number'),
  ('installed_asset','customer_id','STRING','Customer Id','^CUST[0-9]{6}$','customer.customer_id','FK to customer (bronze installed_asset.customer_kunnr)'),
  ('installed_asset','product_id','STRING','Product Id','^MFC-[A-Z]{3}-[0-9]{4}$','product.product_id','FK to product (bronze installed_asset.sku_code)'),
  ('installed_asset','commissioning_status','STRING','Commissioning Status','^(commissioned|pending|failed)$',NULL,'First-install outcome'),
  ('installed_asset','install_date','DATE','Install Date',NULL,NULL,'Date the asset was installed'),
  ('installed_asset','warranty_end_date','DATE','Warranty End Date',NULL,NULL,'Warranty expiry'),
  ('installed_asset','site_country','STRING','Site Country','^[A-Z]{2}$',NULL,'ISO-2 country of the install site'),
  -- customer (Master)
  ('customer','customer_id','STRING','Customer Number','^CUST[0-9]{6}$',NULL,'PK — natural key, SAP kna1.kunnr'),
  ('customer','customer_name','STRING','Customer Name',NULL,NULL,'SAP kna1.name1'),
  ('customer','country_code','STRING','Country Code','^[A-Z]{2}$',NULL,'SAP kna1.land1'),
  ('customer','region','STRING','Region','^(NA|EU|APAC)$',NULL,'SAP kna1.regio'),
  ('customer','industry_code','STRING','Industry Code',NULL,NULL,'SAP kna1.brsch'),
  -- product (Master)
  ('product','product_id','STRING','SKU Code','^MFC-[A-Z]{3}-[0-9]{4}$',NULL,'PK — natural key, installed_asset.sku_code'),
  ('product','product_group','STRING','Product Group','^(valve|actuator|positioner|instrument)$',NULL,'installed_asset.product_group'),
  -- technician (Master — phantom, no bronze source)
  ('technician','technician_id','STRING','Technician Id',NULL,NULL,'PK — no bronze source'),
  ('technician','technician_name','STRING','Technician Name',NULL,NULL,'Free-text name only (service_order.technician) — no master table exists');

-- COMMAND ----------
-- =============================================================================
-- EMPTY TARGET SHELLS — NORMALIZED 3NF product tables the assessment inspects via
-- information_schema (Phase 1.4-1.6). Empty (0 rows), typed, natural-key PK / FK,
-- comments. Both flows read this STRUCTURE and CREATE their own copies in the LAND
-- catalog. technician exists as a shell but has no bronze source.
-- Created in FK-dependency order: customer, product, technician -> installed_asset -> service_order.
-- =============================================================================

CREATE TABLE customer (
  customer_id   STRING NOT NULL COMMENT 'PK — natural key (SAP kna1.kunnr)',
  customer_name STRING COMMENT 'Customer legal name',
  country_code  STRING COMMENT 'ISO-2 country',
  region        STRING COMMENT 'NA | EU | APAC',
  industry_code STRING COMMENT 'Industry key',
  CONSTRAINT pk_customer PRIMARY KEY (customer_id)
) COMMENT 'Customer master (SAP kna1). One row per customer account.';

CREATE TABLE product (
  product_id    STRING NOT NULL COMMENT 'PK — natural key (installed_asset.sku_code)',
  product_group STRING COMMENT 'valve | actuator | positioner | instrument',
  CONSTRAINT pk_product PRIMARY KEY (product_id)
) COMMENT 'Product/SKU master from FieldLink installed-asset attributes. One row per SKU.';

CREATE TABLE technician (
  technician_id   STRING NOT NULL COMMENT 'PK — NO clean bronze source',
  technician_name STRING COMMENT 'Free-text technician name (service_order.technician)',
  CONSTRAINT pk_technician PRIMARY KEY (technician_id)
) COMMENT 'Technician master — INTENTIONALLY unsourced. Bronze has only a free-text name on service_order; no employee master is landed. Expected gap.';

CREATE TABLE installed_asset (
  asset_id             STRING NOT NULL COMMENT 'PK — natural key (FieldLink asset_id)',
  serial_number        STRING COMMENT 'Unit serial number',
  customer_id          STRING COMMENT 'FK to customer',
  product_id           STRING COMMENT 'FK to product',
  commissioning_status STRING COMMENT 'commissioned | pending | failed',
  install_date         DATE   COMMENT 'Install date',
  warranty_end_date    DATE   COMMENT 'Warranty expiry',
  site_country         STRING COMMENT 'ISO-2 country of install site',
  CONSTRAINT pk_installed_asset PRIMARY KEY (asset_id),
  CONSTRAINT fk_asset_customer FOREIGN KEY (customer_id) REFERENCES customer(customer_id),
  CONSTRAINT fk_asset_product  FOREIGN KEY (product_id)  REFERENCES product(product_id)
) COMMENT 'Installed asset master (FieldLink installed_asset). One row per serialized unit.';

CREATE TABLE service_order (
  service_order_id STRING NOT NULL COMMENT 'PK — natural key (FieldLink service_order_id)',
  asset_id         STRING COMMENT 'FK to installed_asset',
  technician_id    STRING COMMENT 'FK to technician — UNRESOLVED (gap: bronze has only a free-text name)',
  order_type       STRING COMMENT 'preventive | corrective | inspection | calibration',
  opened_date      DATE   COMMENT 'Date opened',
  status           STRING COMMENT 'open | dispatched | completed | closed',
  priority         STRING COMMENT 'low | medium | high | critical',
  CONSTRAINT pk_service_order PRIMARY KEY (service_order_id),
  CONSTRAINT fk_so_asset FOREIGN KEY (asset_id)      REFERENCES installed_asset(asset_id),
  CONSTRAINT fk_so_tech  FOREIGN KEY (technician_id) REFERENCES technician(technician_id)
) COMMENT 'Service order (FieldLink service_order). One row per dispatched field-service job.';

-- COMMAND ----------
-- Glossary tags on a few columns so Phase 1.6 (column_tags) returns rows.
ALTER TABLE customer        ALTER COLUMN customer_id      SET TAGS ('glossary_term' = 'Customer Number');
ALTER TABLE installed_asset ALTER COLUMN asset_id         SET TAGS ('glossary_term' = 'Asset Number');
ALTER TABLE service_order   ALTER COLUMN service_order_id SET TAGS ('glossary_term' = 'Service Order Number');

-- COMMAND ----------
-- Verify: metamodel populated, shells empty.
SELECT 'business'  AS t, COUNT(*) AS rows FROM vibe_metamodel_business
UNION ALL SELECT 'product',   COUNT(*) FROM vibe_metamodel_product
UNION ALL SELECT 'attribute', COUNT(*) FROM vibe_metamodel_attribute
UNION ALL SELECT 'service_order (0)',   COUNT(*) FROM service_order
UNION ALL SELECT 'installed_asset (0)', COUNT(*) FROM installed_asset
UNION ALL SELECT 'customer (0)',        COUNT(*) FROM customer
UNION ALL SELECT 'product (0)',         COUNT(*) FROM product
UNION ALL SELECT 'technician (0)',      COUNT(*) FROM technician;
