-- DDL for Business: United Health Care | Version: 1 | Generated on: 2026-03-20 04:03:39

CREATE CATALOG IF NOT EXISTS `cmoore_customer_demos`;

-- ========= DATABASES (DOMAINS) =========
CREATE DATABASE IF NOT EXISTS `cmoore_customer_demos`.`claim` COMMENT 'Core claims processing and adjudication including medical, pharmacy, dental, and vision claims. Manages claim submission (837), editing, pricing, payment processing (835), COB, subrogation, and appeals. Supports CPT, ICD-10, HCPCS, DRG, and APC coding standards. Central to payment accuracy and provider reimbursement.';
CREATE DATABASE IF NOT EXISTS `cmoore_customer_demos`.`member` COMMENT 'Central repository for all member demographics, enrollment status, eligibility periods, coverage history, and member identifiers (subscriber, dependent relationships). Serves as SSOT for all party data including individuals, families, and group associations across all LOBs (Commercial, Medicare, Medicaid). Supports 834 enrollment transactions.';
CREATE DATABASE IF NOT EXISTS `cmoore_customer_demos`.`provider` COMMENT 'Provider network management including physician, hospital, ancillary provider demographics, NPI/TIN identifiers, taxonomy codes, network participation status, and contract affiliations. Supports provider directory, referral management, and network adequacy requirements.';
CREATE DATABASE IF NOT EXISTS `cmoore_customer_demos`.`eligibility` COMMENT 'Real-time eligibility verification, benefit coverage determination, and enrollment transaction processing. Manages eligibility spans, coverage effective dates, termination processing, and COBRA/HIPAA continuation. Supports 270/271 EDI transactions for provider eligibility inquiries.';
CREATE DATABASE IF NOT EXISTS `cmoore_customer_demos`.`product` COMMENT 'Health plan product catalog including HMO, PPO, EPO, POS, HDHP, and government products (MA, MA-PD, PDP, SNP). Defines benefit structures, coverage rules, cost-sharing (deductible, copay, coinsurance, MOOP), formularies, and plan designs across all LOBs with ACA and CMS compliance.';
CREATE DATABASE IF NOT EXISTS `cmoore_customer_demos`.`billing` COMMENT 'Premium billing and revenue collection including group billing, individual billing, premium calculation (PMPM/PEPM), payment processing, grace periods, retroactive adjustments, and accounts receivable. Manages ASO billing, capitation payments, and commission processing.';
CREATE DATABASE IF NOT EXISTS `cmoore_customer_demos`.`authorization` COMMENT 'Prior authorization (PA) and utilization management (UM) including medical necessity review, service authorization requests, approval/denial workflows, concurrent review, and retrospective review. Integrates with InterQual/MCG clinical guidelines for determination logic.';
CREATE DATABASE IF NOT EXISTS `cmoore_customer_demos`.`care` COMMENT 'Care management and disease management programs including care plan development, case management, chronic condition management (HCC), care coordination, member outreach, and population health initiatives. Supports HEDIS quality measures and value-based care programs.';
CREATE DATABASE IF NOT EXISTS `cmoore_customer_demos`.`pharmacy` COMMENT 'Pharmacy benefit management (PBM) including formulary management, drug utilization review (DUR), NDC-based drug catalog, pharmacy claims (NCPDP), AWP/MAC pricing, prior authorization for medications, specialty pharmacy, and mail order programs.';
CREATE DATABASE IF NOT EXISTS `cmoore_customer_demos`.`contract` COMMENT 'Provider contracting and network agreements including fee schedules, capitation arrangements, value-based contracts (VBC), ACO agreements, risk-sharing models, and contract terms. Manages reimbursement methodologies (DRG, APC, fee-for-service) and network adequacy.';
CREATE DATABASE IF NOT EXISTS `cmoore_customer_demos`.`enrollment` COMMENT 'Member enrollment processing including new enrollment, plan changes, qualifying life events (QLE), open enrollment, special enrollment periods (SEP), COBRA continuation, and group enrollment. Manages enrollment through exchanges (FFM/SBM), AEP, and direct channels.';
CREATE DATABASE IF NOT EXISTS `cmoore_customer_demos`.`quality` COMMENT 'Quality measurement and reporting including HEDIS measures, CAHPS surveys, CMS Stars ratings, quality improvement programs, and accreditation compliance (NCQA, URAC). Tracks clinical quality metrics, member satisfaction, and regulatory quality reporting.';
CREATE DATABASE IF NOT EXISTS `cmoore_customer_demos`.`fraud` COMMENT 'Fraud, waste, and abuse (FWA) detection and case management including investigation workflows, Special Investigations Unit (SIU) operations, provider audit findings, overpayment recovery, payment integrity, and referrals to law enforcement.';
CREATE DATABASE IF NOT EXISTS `cmoore_customer_demos`.`risk` COMMENT 'Risk adjustment processing including HCC coding, RAF score calculation, RAPS/EDPS submissions for Medicare Advantage, diagnosis capture, chart reviews, and risk score reconciliation. Supports CMS risk adjustment model compliance and risk-based payment.';
CREATE DATABASE IF NOT EXISTS `cmoore_customer_demos`.`sales` COMMENT 'Sales pipeline management including broker relationships, group sales opportunities, individual enrollment sales, Medicare sales (AEP/OEP), quote generation, proposal management, commission tracking, and lead management across Commercial, Medicare, and Marketplace channels.';
CREATE DATABASE IF NOT EXISTS `cmoore_customer_demos`.`service` COMMENT 'Member and provider customer service including case management, inquiry resolution, grievance and appeals processing, member advocacy, contact center operations, and omnichannel support. Tracks FCR, AHT, NPS, and member satisfaction metrics.';
CREATE DATABASE IF NOT EXISTS `cmoore_customer_demos`.`credentialing` COMMENT 'Provider credentialing and re-credentialing including primary source verification, license validation, board certification, malpractice insurance verification, CAQH data integration, sanctions screening (OIG, SAM), and credentialing committee review.';
CREATE DATABASE IF NOT EXISTS `cmoore_customer_demos`.`finance` COMMENT 'Financial accounting including general ledger (GL), accounts payable (AP), accounts receivable (AR), medical loss ratio (MLR) calculation, financial reporting, statutory filings, actuarial reserves, and regulatory financial filings. Supports GAAP/IFRS compliance and SOX controls.';
CREATE DATABASE IF NOT EXISTS `cmoore_customer_demos`.`compliance` COMMENT 'Regulatory compliance management including HIPAA privacy/security compliance, ACA reporting (1095 forms), CMS program audits, state DOI examinations, ERISA compliance, anti-kickback statute, Stark Law, audit management, and policy enforcement.';
CREATE DATABASE IF NOT EXISTS `cmoore_customer_demos`.`marketing` COMMENT 'Marketing campaign management including member acquisition campaigns, retention programs, digital marketing, broker marketing materials, brand management, AEP campaigns, and marketing performance. Supports Commercial, Medicare, and Marketplace marketing efforts.';
CREATE DATABASE IF NOT EXISTS `cmoore_customer_demos`.`government` COMMENT 'Government programs management including Medicare Advantage, Medicare Part D, Medicaid managed care, dual-eligible programs (D-SNP), and CHIP. Manages CMS regulatory compliance, government contract requirements, and program-specific enrollment and claims processing.';
CREATE DATABASE IF NOT EXISTS `cmoore_customer_demos`.`shared` COMMENT 'Cross-domain shared entities consolidated for Single Source of Truth (SSOT). Contains products that serve multiple business domains.';